#!/usr/bin/env bash
# gen-e2e-env.sh — generate .env.e2e for the hermetic LOCAL e2e harness (A1).
#
# Writes secrets + ports/hostnames consumed by docker-compose.e2e.yml and the
# raw-podman bring-up (e2e-harness/up.sh). IDEMPOTENT: if .env.e2e already
# exists it is reused verbatim (secrets are NOT regenerated — rotating the OIDC
# signing key would invalidate live tokens, and rotating LiveKit/MAS secrets
# would desync running services). chmod 600.
#
# All host ports here are distinct from the running siwx-real-* stack
# (8081/8448/8450) AND the siwx-oidc mock harness (8080/8090).
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="${REPO_ROOT}/.env.e2e"

# Self-signed federation cert for the lk-jwt -> Synapse TLS shim. Independent of
# .env.e2e (no secret-rotation concern), so ensure it on every run, before the
# idempotent early-return below.
"${REPO_ROOT}/scripts/gen-e2e-fed-cert.sh"

if [ -f "${ENV_FILE}" ]; then
  echo "[gen-e2e-env] ${ENV_FILE} already exists — reusing (idempotent)."
  chmod 600 "${ENV_FILE}"
  exit 0
fi

echo "[gen-e2e-env] generating fresh ${ENV_FILE} ..."

MAS_SHARED_SECRET="$(tr -dc A-Za-z0-9 </dev/urandom | head -c 64; echo)"
LIVEKIT_KEY="API$(openssl rand -hex 8)"
LIVEKIT_SECRET="$(openssl rand -base64 32)"

# ES256 (EC P-256) signing key, collapsed to a single line with literal \n so it
# survives shell env passing; siwx-oidc parses the \n-escaped PEM.
PEM_RAW="$(openssl genpkey -algorithm EC -pkeyopt ec_paramgen_curve:P-256 2>/dev/null)"
PEM_ONELINE="$(printf '%s' "${PEM_RAW}" | awk 'BEGIN{ORS="\\n"}{print}')"

umask 077
cat > "${ENV_FILE}" <<EOF
# Generated by scripts/gen-e2e-env.sh — DO NOT COMMIT. chmod 600.
# Hermetic LOCAL e2e harness (siwx-e2eh-*). Ports distinct from siwx-real-* + mock.

# --- secrets ---------------------------------------------------------------
MAS_SHARED_SECRET=${MAS_SHARED_SECRET}
LIVEKIT_KEY=${LIVEKIT_KEY}
LIVEKIT_SECRET=${LIVEKIT_SECRET}
SIWEOIDC_SIGNING_KEY_PEM="${PEM_ONELINE}"

# --- identity / server name -----------------------------------------------
MATRIX_SERVER_NAME=localhost

# --- public (host-facing) URLs --------------------------------------------
# Caddy edge is the single public entrypoint on :18080. The OIDC issuer is
# advertised on :18081 WITH a trailing slash so it byte-matches the issuer
# siwx-oidc derives from SIWEOIDC_BASE_URL (RFC 8414 / RFC 8615 strict match).
CADDY_EDGE_URL=http://localhost:18080
SIWEOIDC_BASE_URL=http://localhost:18081
SIWEOIDC_PUBLIC_ISSUER=http://localhost:18081/
MATRIX_BASE_URL=http://localhost:18080

# --- host port bindings ----------------------------------------------------
CADDY_EDGE_PORT=18080
SIWEOIDC_HOST_PORT=18081
SYNAPSE_HOST_PORT=18448
LIVEKIT_HOST_PORT=7880
LIVEKIT_RTC_TCP_PORT=7881
LIVEKIT_RTC_UDP_START=20100
LIVEKIT_RTC_UDP_END=20200

# --- internal (on-network) endpoints --------------------------------------
SIWEOIDC_INTERNAL_URL=http://siwx-e2eh-oidc:8081
SYNAPSE_INTERNAL_ENDPOINT=http://siwx-e2eh-synapse:8008
REDIS_INTERNAL_URL=redis://siwx-e2eh-redis:6379

# --- logging ---------------------------------------------------------------
RUST_LOG=siwx_oidc=debug,tower_http=info
EOF

chmod 600 "${ENV_FILE}"
echo "[gen-e2e-env] wrote ${ENV_FILE} (chmod 600)."
